<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Auth.IWorkflow\Auth.IWorkflow.csproj" />
    <ProjectReference Include="..\..\Repository\Auth.IRepository\Auth.IRepository.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Riok.Mapperly" Version="3.3.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
